<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2hxTJ7B' shared service.

return $this->privates['.service_locator.2hxTJ7B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'payment' => ['privates', '.errored..service_locator.2hxTJ7B.App\\Entity\\Payment', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\Payment" but no such service exists.'],
], [
    'payment' => 'App\\Entity\\Payment',
]);
