<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.2hxTJ7B.App\Entity\Payment' shared service.

include_once $this->targetDirs[3].'/src/Entity/Payment.php';

return $this->privates['.errored..service_locator.2hxTJ7B.App\\Entity\\Payment'] = new \App\Entity\Payment();
