<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DepRD40' shared service.

return $this->privates['.service_locator.DepRD40'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CampaignController::delete' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController::edit' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController::payment' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController::show' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\ParticipantController::delete' => ['privates', '.service_locator.I8xMv0Y', 'get_ServiceLocator_I8xMv0YService.php', true],
    'App\\Controller\\ParticipantController::edit' => ['privates', '.service_locator.I8xMv0Y', 'get_ServiceLocator_I8xMv0YService.php', true],
    'App\\Controller\\ParticipantController::show' => ['privates', '.service_locator.I8xMv0Y', 'get_ServiceLocator_I8xMv0YService.php', true],
    'App\\Controller\\PaymentController::delete' => ['privates', '.service_locator.2hxTJ7B', 'get_ServiceLocator_2hxTJ7BService.php', true],
    'App\\Controller\\PaymentController::edit' => ['privates', '.service_locator.2hxTJ7B', 'get_ServiceLocator_2hxTJ7BService.php', true],
    'App\\Controller\\PaymentController::new' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\PaymentController::show' => ['privates', '.service_locator.2hxTJ7B', 'get_ServiceLocator_2hxTJ7BService.php', true],
    'App\\Controller\\CampaignController:delete' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController:edit' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController:payment' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\CampaignController:show' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\ParticipantController:delete' => ['privates', '.service_locator.I8xMv0Y', 'get_ServiceLocator_I8xMv0YService.php', true],
    'App\\Controller\\ParticipantController:edit' => ['privates', '.service_locator.I8xMv0Y', 'get_ServiceLocator_I8xMv0YService.php', true],
    'App\\Controller\\ParticipantController:show' => ['privates', '.service_locator.I8xMv0Y', 'get_ServiceLocator_I8xMv0YService.php', true],
    'App\\Controller\\PaymentController:delete' => ['privates', '.service_locator.2hxTJ7B', 'get_ServiceLocator_2hxTJ7BService.php', true],
    'App\\Controller\\PaymentController:edit' => ['privates', '.service_locator.2hxTJ7B', 'get_ServiceLocator_2hxTJ7BService.php', true],
    'App\\Controller\\PaymentController:new' => ['privates', '.service_locator.rlJWk6a', 'get_ServiceLocator_RlJWk6aService.php', true],
    'App\\Controller\\PaymentController:show' => ['privates', '.service_locator.2hxTJ7B', 'get_ServiceLocator_2hxTJ7BService.php', true],
], [
    'App\\Controller\\CampaignController::delete' => '?',
    'App\\Controller\\CampaignController::edit' => '?',
    'App\\Controller\\CampaignController::payment' => '?',
    'App\\Controller\\CampaignController::show' => '?',
    'App\\Controller\\ParticipantController::delete' => '?',
    'App\\Controller\\ParticipantController::edit' => '?',
    'App\\Controller\\ParticipantController::show' => '?',
    'App\\Controller\\PaymentController::delete' => '?',
    'App\\Controller\\PaymentController::edit' => '?',
    'App\\Controller\\PaymentController::new' => '?',
    'App\\Controller\\PaymentController::show' => '?',
    'App\\Controller\\CampaignController:delete' => '?',
    'App\\Controller\\CampaignController:edit' => '?',
    'App\\Controller\\CampaignController:payment' => '?',
    'App\\Controller\\CampaignController:show' => '?',
    'App\\Controller\\ParticipantController:delete' => '?',
    'App\\Controller\\ParticipantController:edit' => '?',
    'App\\Controller\\ParticipantController:show' => '?',
    'App\\Controller\\PaymentController:delete' => '?',
    'App\\Controller\\PaymentController:edit' => '?',
    'App\\Controller\\PaymentController:new' => '?',
    'App\\Controller\\PaymentController:show' => '?',
]);
