<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rlJWk6a' shared service.

return $this->privates['.service_locator.rlJWk6a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'campaign' => ['privates', '.errored..service_locator.rlJWk6a.App\\Entity\\Campaign', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\Campaign" but no such service exists.'],
], [
    'campaign' => 'App\\Entity\\Campaign',
]);
